### ISSUE TITLE
源码安装部署报错,这是什么原因?

### ISSUE THREAD

**Issue by Sirzhangsheng** [Clouditera/SecGPT#27]
ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

**Comment by Sirzhangsheng** [comment]
Traceback (most recent call last):
  File "webdemo.py", line 207, in <module>
    main(args.base_model, args.share_gradio)
  File "webdemo.py", line 75, in main
    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)
  File "/opt/anaconda3/envs/secgpt-mini/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 689, in from_pretrained
    f"Tokenizer class {tokenizer_class_candidate} does not exist or is not currently imported."
ValueError: Tokenizer class Qwen2Tokenizer does not exist or is not currently imported.

**Comment by Sundogs8603** [comment]
是不是transformerer版本的问题，升级transformers>=4.37.0 ：pip install transformer -U

**Comment by Sirzhangsheng** [comment]
> 是不是transformerer版本的问题，升级transformers>=4.37.0 ：pip install transformer -U

试过了，也重新卸载尝试了，也不行，我今天在windows电脑上用的python 3.11是成功运行了。晚点再看一下

**Comment by donyzhai** [comment]
你好，请问你问题解决没 我也遇到了这个问题，升级Transformers也不行

**Comment by medasz** [comment]
我也遇到了，我用的3.7.9版本的python

**Comment by medasz** [comment]
我换了python3.12.4就可以了
