### ISSUE TITLE
secgpt-mini 部署失败

### ISSUE THREAD

**Issue by Cirno9-dev** [Clouditera/SecGPT#29]
docker 和本机部署都会出现以下问题：
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/ljx/Projects/Subject/secgpt-mini/webdemo.py", line 207, in <module>
    main(args.base_model, args.share_gradio)
  File "/home/ljx/Projects/Subject/secgpt-mini/webdemo.py", line 76, in main
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ljx/.virtualenvs/secgpt/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ljx/.virtualenvs/secgpt/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3284, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**环境**
* archlinux 6.7.8-arch1-1
* python 3.11.8
* transformer 4.38.2

**Comment by Cirno9-dev** [comment]
问题解决了。
git lfs 没有把模型下载下来。

**Comment by knighttt7** [comment]
请问有mini模型的下载方法吗，readme给的链接里没有mini模型

**Comment by Cirno9-dev** [comment]
模型就是那个 model.safetensors：
![屏幕截图 2024-05-24 172427](https://github.com/Clouditera/SecGPT/assets/48610257/add8a86a-4bca-4420-a93d-74e40682ac1d)
如果使用 git 来 clone，得使用 git lfs 来下载。
