### ISSUE TITLE
secgpt mini 只能短暂运行几秒，几秒后页面报错，进程退出

### ISSUE THREAD

**Issue by linzhihui7** [Clouditera/SecGPT#33]
求助！！

![image](https://github.com/Clouditera/SecGPT/assets/122329515/e5e3dc62-55fb-4224-a3b1-3e8bf6cfa733)

```bash
-> # python3 secgpt-mini/webdemo.py --base_model secgpt-mini/models
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Running on local URL:  http://0.0.0.0:7860
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/secgpt-mini/webdemo.py", line 207, in <module>
    main(args.base_model, args.share_gradio)
  File "/root/secgpt-mini/webdemo.py", line 196, in main
    demo.queue().launch(server_name="0.0.0.0", share=share_gradio)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2087, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 198, in get
    return request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
terminate called without an active exception
[1]    62279 IOT instruction (core dumped)  python3 secgpt-mini/webdemo.py --base_model secgpt-mini/models

```

**Comment by boy-hack** [comment]
暂不清楚为什么，试试docker方案呢

**Comment by caomeng528** [comment]
webdemo.py: error: the following arguments are required: --base_model
你好，我跟着执行，然后出现这个，啥原因呢

**Comment by smartzh** [comment]
我用python3.8跑问题

**Comment by lzl-hello** [comment]
> 暂不清楚为什么，试试docker方案呢

大佬，我想请教一下docker方案部署mini版本的步骤，我看文档就给了dockerfile，需要下载模型和源码吗？在哪里下载呢
