### ISSUE TITLE
提交指令时出现报错，ValueError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nextcup** [Clouditera/SecGPT#39]
# 1.使用了baichuan13项目中的量化方法
```
    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        # device_map=device,
        trust_remote_code=True,
        torch_dtype=torch.float16
    )
    model = model.quantize(4).cuda()
```
# 2.启动webdemo后CPU占用22GB，GPU 2GB
# 3.提交指令时出现报错，ValueError: Expecting value: line 1 column 1 (char 0)
```
(secgpt) C:\PycharmProjects\SecGPT-main\webdemo>python client_api.py
Loaded as API: http://127.0.0.1:7860/ ✔
Traceback (most recent call last):
  File "C:\PycharmProjects\SecGPT-main\webdemo\client_api.py", line 4, in <module>
    result = client.predict(
             ^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\site-packages\gradio_client\client.py", line 424, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\site-packages\gradio_client\client.py", line 1311, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\site-packages\gradio_client\compatibility.py", line 65, in _inner
    predictions = _predict(*data)
                  ^^^^^^^^^^^^^^^
  File "C:\tools\python\miniconda3\envs\secgpt\Lib\site-packages\gradio_client\compatibility.py", line 95, in _predict
    raise ValueError(result["error"])
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by nextcup** [comment]
找到原因了，是因为gradio_client版本太低，需要升级gradio_client和gradio。 
pip install --upgrade gradio gradio_client
